apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
  namespace: springboot-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
    template:
      matadata:
        name: hello-pod
        labels:
          app: spring-boot-app
        spec:
          containers:
            - name: app
              image: cart-spring-boot:latest
              ports:
                -containerPort: 8080
              imagePullPolicy: Always

