apiVersion: v1
kind: Service
metadata:
  name: springboot-configmap-secret-deployment-service
spec:
  selector:
    app: springboot-k8s
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer


